### ISSUE TITLE
Is it possible to use this plugin from doctest?

### ISSUE THREAD

**Issue by minad** [LeventErkok/sbvPlugin#17]
I am wondering if it is possible to run this as a doctest tool instead of a GHC plugin? What is the reason for hooking into the GHC pipeline?

**Comment by LeventErkok** [comment]
@minad The prover works on GHC-core; so it makes the most sense to hook it up as a compiler-plugin.

Having said that, I'm sure it can be hooked-up as a doctest tool with some engineering as well. Feel free to submit a patch if you do so!

**Comment by minad** [comment]
Ah I understand. Makes sense then. Probably one could take the liquidhaskell approach if one wants to create a separate tool (assuming that they work on core too).

How does this project compare to liquidhaskell btw? I am also quite confused with the many different bindings to SMT solvers, sbv, smtlib2, smtLib, SmtLib and liquidhaskell rolls there own I guess.

**Comment by LeventErkok** [comment]
As is usual with Hackage, there are many packages that overlap in their functionality. LiquidHaskell is quite different actually from SBV. SMTLib/SMTLib2 etc., are lower level interfaces than what SBV targets for, but they might be more suitable depending on what your goals are. I'm not too familiar with all the differences.

This sort of discussion comes up quite often actually on reddit and other places; you might want to read through some of the comments here: https://www.reddit.com/r/haskell/comments/1y3llk/new_release_of_sbv_with_support_for_reasoning/?st=iqibypwj&sh=4a33f4ba

**Comment by minad** [comment]
Thx for your answer and the great explanation on reddit, haven't seen that before. Right now I am using SBV as DSL and it works like a breeze!

**Comment by LeventErkok** [comment]
Fantastic. I'm closing this ticket then; if you run into problems, feel free to open new tickets, either here, or at the github site for sbv itself: https://github.com/LeventErkok/sbv
